// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
// Version: 2021.2
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module hash_controller_egress_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        egress_1_TVALID,
        m_axi_wr_1_AWVALID,
        m_axi_wr_1_AWREADY,
        m_axi_wr_1_AWADDR,
        m_axi_wr_1_AWID,
        m_axi_wr_1_AWLEN,
        m_axi_wr_1_AWSIZE,
        m_axi_wr_1_AWBURST,
        m_axi_wr_1_AWLOCK,
        m_axi_wr_1_AWCACHE,
        m_axi_wr_1_AWPROT,
        m_axi_wr_1_AWQOS,
        m_axi_wr_1_AWREGION,
        m_axi_wr_1_AWUSER,
        m_axi_wr_1_WVALID,
        m_axi_wr_1_WREADY,
        m_axi_wr_1_WDATA,
        m_axi_wr_1_WSTRB,
        m_axi_wr_1_WLAST,
        m_axi_wr_1_WID,
        m_axi_wr_1_WUSER,
        m_axi_wr_1_ARVALID,
        m_axi_wr_1_ARREADY,
        m_axi_wr_1_ARADDR,
        m_axi_wr_1_ARID,
        m_axi_wr_1_ARLEN,
        m_axi_wr_1_ARSIZE,
        m_axi_wr_1_ARBURST,
        m_axi_wr_1_ARLOCK,
        m_axi_wr_1_ARCACHE,
        m_axi_wr_1_ARPROT,
        m_axi_wr_1_ARQOS,
        m_axi_wr_1_ARREGION,
        m_axi_wr_1_ARUSER,
        m_axi_wr_1_RVALID,
        m_axi_wr_1_RREADY,
        m_axi_wr_1_RDATA,
        m_axi_wr_1_RLAST,
        m_axi_wr_1_RID,
        m_axi_wr_1_RFIFONUM,
        m_axi_wr_1_RUSER,
        m_axi_wr_1_RRESP,
        m_axi_wr_1_BVALID,
        m_axi_wr_1_BREADY,
        m_axi_wr_1_BRESP,
        m_axi_wr_1_BID,
        m_axi_wr_1_BUSER,
        golden_fifo_1_TREADY,
        gmem,
        egress_1_TDATA,
        egress_1_TREADY,
        egress_1_TKEEP,
        egress_1_TSTRB,
        egress_1_TLAST,
        egress_1_TDEST,
        last,
        target,
        golden_fifo_1_TDATA,
        golden_fifo_1_TVALID
);

parameter    ap_ST_fsm_pp0_stage0 = 2'd1;
parameter    ap_ST_fsm_pp0_stage1 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input   egress_1_TVALID;
output   m_axi_wr_1_AWVALID;
input   m_axi_wr_1_AWREADY;
output  [63:0] m_axi_wr_1_AWADDR;
output  [0:0] m_axi_wr_1_AWID;
output  [31:0] m_axi_wr_1_AWLEN;
output  [2:0] m_axi_wr_1_AWSIZE;
output  [1:0] m_axi_wr_1_AWBURST;
output  [1:0] m_axi_wr_1_AWLOCK;
output  [3:0] m_axi_wr_1_AWCACHE;
output  [2:0] m_axi_wr_1_AWPROT;
output  [3:0] m_axi_wr_1_AWQOS;
output  [3:0] m_axi_wr_1_AWREGION;
output  [0:0] m_axi_wr_1_AWUSER;
output   m_axi_wr_1_WVALID;
input   m_axi_wr_1_WREADY;
output  [255:0] m_axi_wr_1_WDATA;
output  [31:0] m_axi_wr_1_WSTRB;
output   m_axi_wr_1_WLAST;
output  [0:0] m_axi_wr_1_WID;
output  [0:0] m_axi_wr_1_WUSER;
output   m_axi_wr_1_ARVALID;
input   m_axi_wr_1_ARREADY;
output  [63:0] m_axi_wr_1_ARADDR;
output  [0:0] m_axi_wr_1_ARID;
output  [31:0] m_axi_wr_1_ARLEN;
output  [2:0] m_axi_wr_1_ARSIZE;
output  [1:0] m_axi_wr_1_ARBURST;
output  [1:0] m_axi_wr_1_ARLOCK;
output  [3:0] m_axi_wr_1_ARCACHE;
output  [2:0] m_axi_wr_1_ARPROT;
output  [3:0] m_axi_wr_1_ARQOS;
output  [3:0] m_axi_wr_1_ARREGION;
output  [0:0] m_axi_wr_1_ARUSER;
input   m_axi_wr_1_RVALID;
output   m_axi_wr_1_RREADY;
input  [255:0] m_axi_wr_1_RDATA;
input   m_axi_wr_1_RLAST;
input  [0:0] m_axi_wr_1_RID;
input  [8:0] m_axi_wr_1_RFIFONUM;
input  [0:0] m_axi_wr_1_RUSER;
input  [1:0] m_axi_wr_1_RRESP;
input   m_axi_wr_1_BVALID;
output   m_axi_wr_1_BREADY;
input  [1:0] m_axi_wr_1_BRESP;
input  [0:0] m_axi_wr_1_BID;
input  [0:0] m_axi_wr_1_BUSER;
input   golden_fifo_1_TREADY;
input  [63:0] gmem;
input  [511:0] egress_1_TDATA;
output   egress_1_TREADY;
input  [63:0] egress_1_TKEEP;
input  [63:0] egress_1_TSTRB;
input  [0:0] egress_1_TLAST;
input  [0:0] egress_1_TDEST;
input  [0:0] last;
input  [511:0] target;
output  [31:0] golden_fifo_1_TDATA;
output   golden_fifo_1_TVALID;

reg ap_idle;
reg m_axi_wr_1_AWVALID;
reg m_axi_wr_1_WVALID;
reg[255:0] m_axi_wr_1_WDATA;
reg m_axi_wr_1_BREADY;
reg egress_1_TREADY;
reg golden_fifo_1_TVALID;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage1;
reg   [0:0] icmp_ln29_reg_280;
reg    ap_block_state2_pp0_stage1_iter0;
reg   [0:0] last_read_reg_276;
reg    ap_predicate_op41_writereq_state2;
reg    ap_block_state2_io;
wire    ap_block_state4_pp0_stage1_iter1;
reg   [0:0] last_read_reg_276_pp0_iter1_reg;
reg    ap_block_state4_io;
wire    ap_block_state6_pp0_stage1_iter2;
reg   [0:0] last_read_reg_276_pp0_iter3_reg;
reg   [0:0] icmp_ln1072_reg_307;
reg   [0:0] icmp_ln1072_reg_307_pp0_iter2_reg;
reg    ap_predicate_op54_write_state8;
reg    ap_block_state8_pp0_stage1_iter3;
reg    ap_block_state8_io;
reg    ap_done_reg;
reg    ap_block_pp0_stage1_subdone;
reg    ap_condition_exit_pp0_iter0_stage1;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    wr_1_blk_n_AW;
wire    ap_block_pp0_stage1;
reg    wr_1_blk_n_W;
wire    ap_block_pp0_stage0;
reg    wr_1_blk_n_B;
reg    egress_1_TDATA_blk_n;
reg    golden_fifo_1_TDATA_blk_n;
reg   [511:0] target_read_reg_271;
reg    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state3_pp0_stage0_iter1;
reg    ap_block_state3_io;
wire    ap_block_state5_pp0_stage0_iter2;
wire    ap_block_state7_pp0_stage0_iter3;
reg    ap_block_state9_pp0_stage0_iter4;
reg    ap_block_pp0_stage0_11001;
wire   [0:0] last_read_read_fu_106_p2;
reg   [0:0] last_read_reg_276_pp0_iter2_reg;
wire   [0:0] icmp_ln29_fu_171_p2;
reg   [0:0] icmp_ln29_reg_280_pp0_iter1_reg;
reg   [0:0] icmp_ln29_reg_280_pp0_iter2_reg;
wire   [24:0] trunc_ln293_fu_183_p1;
reg   [24:0] trunc_ln293_reg_284;
reg   [24:0] trunc_ln293_reg_284_pp0_iter1_reg;
reg   [24:0] trunc_ln293_reg_284_pp0_iter2_reg;
reg   [24:0] trunc_ln293_reg_284_pp0_iter3_reg;
reg   [58:0] trunc_ln_reg_289;
reg   [511:0] tmp_data_V_reg_294;
reg    ap_block_pp0_stage1_11001;
wire   [0:0] icmp_ln1072_fu_234_p2;
reg   [0:0] icmp_ln1072_reg_307_pp0_iter1_reg;
reg   [255:0] p_Result_s_reg_311;
reg    ap_enable_reg_pp0_iter0_reg;
reg    ap_block_pp0_stage0_subdone;
wire  signed [63:0] sext_ln35_fu_224_p1;
wire   [255:0] trunc_ln674_fu_239_p1;
reg    ap_block_pp0_stage0_01001;
reg    ap_block_pp0_stage1_01001;
reg   [25:0] i_fu_96;
wire   [25:0] add_ln29_fu_177_p2;
wire    ap_loop_init;
reg   [25:0] ap_sig_allocacmp_i_3;
wire   [30:0] shl_ln_fu_187_p3;
wire   [63:0] zext_ln293_fu_195_p1;
wire   [63:0] add_ln293_fu_199_p2;
wire   [25:0] or_ln_fu_252_p3;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_condition_exit_pp0_iter3_stage0;
reg    ap_idle_pp0_0to2;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg   [1:0] ap_NS_fsm;
reg    ap_idle_pp0_1to4;
wire    ap_enable_pp0;
wire    ap_start_int;
reg    ap_condition_314;
reg    ap_condition_439;
reg    ap_condition_443;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
end

hash_controller_flow_control_loop_pipe flow_control_loop_pipe_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage1),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int),
    .ap_continue(ap_continue)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter3_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage1)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter4 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to2 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter3_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to2 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter3_stage0))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to2 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter3_stage0))) begin
        ap_loop_exit_ready_pp0_iter3_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_314)) begin
        if ((icmp_ln29_fu_171_p2 == 1'd0)) begin
            i_fu_96 <= add_ln29_fu_177_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_96 <= 26'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln29_reg_280 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001) & (last_read_reg_276 == 1'd1))) begin
        icmp_ln1072_reg_307 <= icmp_ln1072_fu_234_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        icmp_ln1072_reg_307_pp0_iter1_reg <= icmp_ln1072_reg_307;
        icmp_ln1072_reg_307_pp0_iter2_reg <= icmp_ln1072_reg_307_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        icmp_ln29_reg_280 <= icmp_ln29_fu_171_p2;
        icmp_ln29_reg_280_pp0_iter1_reg <= icmp_ln29_reg_280;
        icmp_ln29_reg_280_pp0_iter2_reg <= icmp_ln29_reg_280_pp0_iter1_reg;
        last_read_reg_276 <= last;
        last_read_reg_276_pp0_iter1_reg <= last_read_reg_276;
        last_read_reg_276_pp0_iter2_reg <= last_read_reg_276_pp0_iter1_reg;
        last_read_reg_276_pp0_iter3_reg <= last_read_reg_276_pp0_iter2_reg;
        target_read_reg_271 <= target;
        trunc_ln293_reg_284_pp0_iter1_reg <= trunc_ln293_reg_284;
        trunc_ln293_reg_284_pp0_iter2_reg <= trunc_ln293_reg_284_pp0_iter1_reg;
        trunc_ln293_reg_284_pp0_iter3_reg <= trunc_ln293_reg_284_pp0_iter2_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (last_read_reg_276 == 1'd0))) begin
        p_Result_s_reg_311 <= {{tmp_data_V_reg_294[511:256]}};
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln29_reg_280 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        tmp_data_V_reg_294 <= egress_1_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln29_fu_171_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        trunc_ln293_reg_284 <= trunc_ln293_fu_183_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln29_fu_171_p2 == 1'd0) & (last_read_read_fu_106_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        trunc_ln_reg_289 <= {{add_ln293_fu_199_p2[63:5]}};
    end
end

always @ (*) begin
    if (((icmp_ln29_reg_280 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln29_reg_280_pp0_iter2_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_exit_pp0_iter3_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter3_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter3_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0_0to2 = 1'b1;
    end else begin
        ap_idle_pp0_0to2 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0_1to4 = 1'b1;
    end else begin
        ap_idle_pp0_1to4 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_i_3 = 26'd0;
    end else begin
        ap_sig_allocacmp_i_3 = i_fu_96;
    end
end

always @ (*) begin
    if (((icmp_ln29_reg_280 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1))) begin
        egress_1_TDATA_blk_n = egress_1_TVALID;
    end else begin
        egress_1_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln29_reg_280 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        egress_1_TREADY = 1'b1;
    end else begin
        egress_1_TREADY = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1) & (ap_predicate_op54_write_state8 == 1'b1))) begin
        golden_fifo_1_TDATA_blk_n = golden_fifo_1_TREADY;
    end else begin
        golden_fifo_1_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_predicate_op54_write_state8 == 1'b1))) begin
        golden_fifo_1_TVALID = 1'b1;
    end else begin
        golden_fifo_1_TVALID = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_predicate_op41_writereq_state2 == 1'b1))) begin
        m_axi_wr_1_AWVALID = 1'b1;
    end else begin
        m_axi_wr_1_AWVALID = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (last_read_reg_276_pp0_iter3_reg == 1'd0))) begin
        m_axi_wr_1_BREADY = 1'b1;
    end else begin
        m_axi_wr_1_BREADY = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
        if ((1'b1 == ap_condition_443)) begin
            m_axi_wr_1_WDATA = p_Result_s_reg_311;
        end else if ((1'b1 == ap_condition_439)) begin
            m_axi_wr_1_WDATA = trunc_ln674_fu_239_p1;
        end else begin
            m_axi_wr_1_WDATA = 'bx;
        end
    end else begin
        m_axi_wr_1_WDATA = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001) & (last_read_reg_276_pp0_iter1_reg == 1'd0)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (last_read_reg_276 == 1'd0)))) begin
        m_axi_wr_1_WVALID = 1'b1;
    end else begin
        m_axi_wr_1_WVALID = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1) & (ap_predicate_op41_writereq_state2 == 1'b1))) begin
        wr_1_blk_n_AW = m_axi_wr_1_AWREADY;
    end else begin
        wr_1_blk_n_AW = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0) & (last_read_reg_276_pp0_iter3_reg == 1'd0))) begin
        wr_1_blk_n_B = m_axi_wr_1_BVALID;
    end else begin
        wr_1_blk_n_B = 1'b1;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1) & (last_read_reg_276_pp0_iter1_reg == 1'd0)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0) & (last_read_reg_276 == 1'd0)))) begin
        wr_1_blk_n_W = m_axi_wr_1_WREADY;
    end else begin
        wr_1_blk_n_W = 1'b1;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if (((ap_idle_pp0_0to2 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter3_stage0))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((~((ap_start_int == 1'b0) & (ap_idle_pp0_1to4 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln293_fu_199_p2 = (zext_ln293_fu_195_p1 + gmem);

assign add_ln29_fu_177_p2 = (ap_sig_allocacmp_i_3 + 26'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((m_axi_wr_1_BVALID == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b1) & (last_read_reg_276_pp0_iter3_reg == 1'd0)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (ap_done_reg == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((m_axi_wr_1_BVALID == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b1) & (last_read_reg_276_pp0_iter3_reg == 1'd0)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state3_io)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (ap_done_reg == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((m_axi_wr_1_BVALID == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b1) & (last_read_reg_276_pp0_iter3_reg == 1'd0)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state3_io)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (ap_done_reg == 1'b1)));
end

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_01001 = ((ap_done_reg == 1'b1) | ((icmp_ln29_reg_280 == 1'd0) & (egress_1_TVALID == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((ap_enable_reg_pp0_iter3 == 1'b1) & (ap_predicate_op54_write_state8 == 1'b1) & (golden_fifo_1_TREADY == 1'b0)));
end

always @ (*) begin
    ap_block_pp0_stage1_11001 = ((ap_done_reg == 1'b1) | ((ap_enable_reg_pp0_iter3 == 1'b1) & ((1'b1 == ap_block_state8_io) | ((ap_predicate_op54_write_state8 == 1'b1) & (golden_fifo_1_TREADY == 1'b0)))) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state4_io)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & ((1'b1 == ap_block_state2_io) | ((icmp_ln29_reg_280 == 1'd0) & (egress_1_TVALID == 1'b0)))));
end

always @ (*) begin
    ap_block_pp0_stage1_subdone = ((ap_done_reg == 1'b1) | ((ap_enable_reg_pp0_iter3 == 1'b1) & ((1'b1 == ap_block_state8_io) | ((ap_predicate_op54_write_state8 == 1'b1) & (golden_fifo_1_TREADY == 1'b0)))) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state4_io)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & ((1'b1 == ap_block_state2_io) | ((icmp_ln29_reg_280 == 1'd0) & (egress_1_TVALID == 1'b0)))));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_done_reg == 1'b1);
end

always @ (*) begin
    ap_block_state2_io = ((m_axi_wr_1_AWREADY == 1'b0) & (ap_predicate_op41_writereq_state2 == 1'b1));
end

always @ (*) begin
    ap_block_state2_pp0_stage1_iter0 = ((icmp_ln29_reg_280 == 1'd0) & (egress_1_TVALID == 1'b0));
end

always @ (*) begin
    ap_block_state3_io = ((m_axi_wr_1_WREADY == 1'b0) & (last_read_reg_276 == 1'd0));
end

assign ap_block_state3_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state4_io = ((m_axi_wr_1_WREADY == 1'b0) & (last_read_reg_276_pp0_iter1_reg == 1'd0));
end

assign ap_block_state4_pp0_stage1_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage1_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state8_io = ((ap_predicate_op54_write_state8 == 1'b1) & (golden_fifo_1_TREADY == 1'b0));
end

always @ (*) begin
    ap_block_state8_pp0_stage1_iter3 = ((ap_predicate_op54_write_state8 == 1'b1) & (golden_fifo_1_TREADY == 1'b0));
end

always @ (*) begin
    ap_block_state9_pp0_stage0_iter4 = ((m_axi_wr_1_BVALID == 1'b0) & (last_read_reg_276_pp0_iter3_reg == 1'd0));
end

always @ (*) begin
    ap_condition_314 = ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001));
end

always @ (*) begin
    ap_condition_439 = ((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_01001) & (last_read_reg_276 == 1'd0));
end

always @ (*) begin
    ap_condition_443 = ((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_01001) & (last_read_reg_276_pp0_iter1_reg == 1'd0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage1;

always @ (*) begin
    ap_predicate_op41_writereq_state2 = ((icmp_ln29_reg_280 == 1'd0) & (last_read_reg_276 == 1'd0));
end

always @ (*) begin
    ap_predicate_op54_write_state8 = ((icmp_ln1072_reg_307_pp0_iter2_reg == 1'd1) & (last_read_reg_276_pp0_iter3_reg == 1'd1));
end

assign golden_fifo_1_TDATA = or_ln_fu_252_p3;

assign icmp_ln1072_fu_234_p2 = ((egress_1_TDATA < target_read_reg_271) ? 1'b1 : 1'b0);

assign icmp_ln29_fu_171_p2 = ((ap_sig_allocacmp_i_3 == 26'd33554432) ? 1'b1 : 1'b0);

assign last_read_read_fu_106_p2 = last;

assign m_axi_wr_1_ARADDR = 64'd0;

assign m_axi_wr_1_ARBURST = 2'd0;

assign m_axi_wr_1_ARCACHE = 4'd0;

assign m_axi_wr_1_ARID = 1'd0;

assign m_axi_wr_1_ARLEN = 32'd0;

assign m_axi_wr_1_ARLOCK = 2'd0;

assign m_axi_wr_1_ARPROT = 3'd0;

assign m_axi_wr_1_ARQOS = 4'd0;

assign m_axi_wr_1_ARREGION = 4'd0;

assign m_axi_wr_1_ARSIZE = 3'd0;

assign m_axi_wr_1_ARUSER = 1'd0;

assign m_axi_wr_1_ARVALID = 1'b0;

assign m_axi_wr_1_AWADDR = sext_ln35_fu_224_p1;

assign m_axi_wr_1_AWBURST = 2'd0;

assign m_axi_wr_1_AWCACHE = 4'd0;

assign m_axi_wr_1_AWID = 1'd0;

assign m_axi_wr_1_AWLEN = 32'd2;

assign m_axi_wr_1_AWLOCK = 2'd0;

assign m_axi_wr_1_AWPROT = 3'd0;

assign m_axi_wr_1_AWQOS = 4'd0;

assign m_axi_wr_1_AWREGION = 4'd0;

assign m_axi_wr_1_AWSIZE = 3'd0;

assign m_axi_wr_1_AWUSER = 1'd0;

assign m_axi_wr_1_RREADY = 1'b0;

assign m_axi_wr_1_WID = 1'd0;

assign m_axi_wr_1_WLAST = 1'b0;

assign m_axi_wr_1_WSTRB = 32'd4294967295;

assign m_axi_wr_1_WUSER = 1'd0;

assign or_ln_fu_252_p3 = {{1'd1}, {trunc_ln293_reg_284_pp0_iter3_reg}};

assign sext_ln35_fu_224_p1 = $signed(trunc_ln_reg_289);

assign shl_ln_fu_187_p3 = {{trunc_ln293_fu_183_p1}, {6'd0}};

assign trunc_ln293_fu_183_p1 = ap_sig_allocacmp_i_3[24:0];

assign trunc_ln674_fu_239_p1 = tmp_data_V_reg_294[255:0];

assign zext_ln293_fu_195_p1 = shl_ln_fu_187_p3;

endmodule //hash_controller_egress_1
